### PR TITLE
Refactor emails

### PR DESCRIPTION
**Pull request by IliaWithHat**
## Summary of change

- Rewrited all emails templates to match with GreenCity project: used right logo, fonts, colors.
- Added localization.
- Removed unused/unnecessary code/DTO.

### CODE REVIEW

**Review by KizerovDmitriy — APPROVED** [review]

**Comment by KizerovDmitriy** [comment]
please resolve 5 issues

**Comment by IliaWithHat** [comment]
> please resolve 5 issues

Every issue needed.

**Comment by KizerovDmitriy** [comment]
resolve issues where need to define a constant, TODO stay without changes.

**Review by holotsvan — APPROVED** [review]

**Comment by IliaWithHat** [comment]
> resolve issues where need to define a constant, TODO stay without changes.

Done.

**Review by lukovskyj — APPROVED** [review]

**Pull request merged**
